module.exports.AuthRoutes = require('./auth')
module.exports.AboutMeRoutes = require('./aboutMe')
module.exports.AdvertRoutes = require('./advert')
module.exports.AdvertTypeRoutes = require('./advertType')
module.exports.FavoriteRoutes = require('./favorite')
module.exports.OfferRoutes = require('./offer')